remote_theme: devich/quick@0.0.1
bg_color: dark
theme_color: azure
title: Auto VIT Wi-Fi
description: Auto VIT Wi-Fi is a sleek browser extension that detects if you're connected to VIT Wi-Fi and automatically logs in to the network portal

keywords: Auto VWIFI, Autologin, Firefox, Chrome, VIT, Auto VIT WIFI, phc.prontonetworks.com